#include <stdio.h>

#include "trampoline.h"

#define MOVE_TO_REGISTER(reg) \
    __asm__("movq %0, %%" reg \
        : \
        : "r"(arg) \
        : reg \
    )

#define MOVE_TO_FLOAT_REGISTER(reg) \
    __asm__("movss %%" reg ", %0" \
        : \
        : "m"(arg) \
        : reg \
    )

void *
call(void *f, void **args, int *flags, int count)
{
    void *ret;
    int ii;
    int ireg = 0;
    int freg = 0;
    for (ii = 0; ii < count; ii++) {
        void *arg = args[ii];
        int flag = flags[ii];
        if (flag & ARG_FLAG_FLOAT) {
            switch (freg) {
                case 0:
                    MOVE_TO_FLOAT_REGISTER("xmm0");
                    break;
                case 1:
                    MOVE_TO_FLOAT_REGISTER("xmm1");
                    break;
                case 2:
                    MOVE_TO_FLOAT_REGISTER("xmm2");
                    break;
                case 3:
                    MOVE_TO_FLOAT_REGISTER("xmm3");
                    break;
                case 4:
                    MOVE_TO_FLOAT_REGISTER("xmm4");
                    break;
                case 5:
                    MOVE_TO_FLOAT_REGISTER("xmm5");
                    break;
                case 6:
                    MOVE_TO_FLOAT_REGISTER("xmm6");
                    break;
                case 7:
                    MOVE_TO_FLOAT_REGISTER("xmm7");
                    break;
                default:
                    fprintf(stderr, "%s\n", "can bind more than 8 float args");
            }
            freg++;
            continue;
        }
        switch (ireg) {
            case 0:
                MOVE_TO_REGISTER("rdi");
                break;
            case 1:
                MOVE_TO_REGISTER("rsi");
                break;
            case 2:
                MOVE_TO_REGISTER("rdx");
                break;
            case 3:
                MOVE_TO_REGISTER("rcx");
                break;
            case 4:
                MOVE_TO_REGISTER("r8");
                break;
            case 5:
                MOVE_TO_REGISTER("r9");
                break;
            default:
                fprintf(stderr, "%s\n", "can bind more than 6 integer/pointer args");
        }
        ireg++;
        continue;
    }
    // Call function and get rax before doing anything
    // else, otherwise the register might get overwritten
    // by the code generated by the if.
    __asm__("call *%0;"
        :
        : "r"(f)
        : "rax", "rbx", "rcx", "rdx", "rsp", "rbp", "rsi", "rdi", "r8", "r9", "r10", "r11"
    );
    __asm__("movq %%rax, %0"
        : "=r" (ret)
    );
    if (flags[count] & ARG_FLAG_FLOAT) {
        __asm__("movq %%xmm0, %0"
            : "=r" (ret)
        );
    }
    return ret;
}
